export default {
    FETCH_USERS_REQUEST:"FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCES:"FETCH_USERS_SUCCES",
    FETCH_USERS_FAIL:"FETCH_USERS_FAIL",
    DELETE_USERS_REQUEST:"DELETE_USERS_REQUEST",
    DELETE_USERS_SUCCES:"DELETE_USERS_SUCCES",
    DELETE_USERS_FAIL:"DELETE_USERS_FAIL",
    EDIT_USERS_REQUEST:"EDIT_USERS_REQUEST",
    EDIT_USERS_SUCCES:"EDIT_USERS_SUCCES",
    EDIT_USERS_FAIL:"EDIT_USERS_FAIL"
}